namespace LineStatus.Api.Models.Entities;

public class cds_service
{
    public int service_id { get; set; }
    public string service_code { get; set; }
    public int service_position { get; set; }
    public int service_haschild { get; set; }
    public int service_parent { get; set; }
    public int service_servtime { get; set; }
    public int service_desknr { get; set; }
    public int service_active { get; set; }
    public int service_deleted { get; set; }
    public int service_critical_clients { get; set; }
    public int service_visible { get; set; }
    public int service_registered { get; set; }
    public int service_main_id { get; set; }
    public int service_ticket_id { get; set; }
    public int service_button_id { get; set; }
    public int service_give_ticket { get; set; }
    public int service_mainframe_id { get; set; }
    public int service_show_waiting_clients { get; set; }
    public int service_has_agent_selection { get; set; }
    public char service_keyboard_shortcut { get; set; }
    public int service_show_approval_form { get; set; }
    public int service_ask_numeric_code { get; set; }
    public int service_numeric_code_length { get; set; }
    public int service_type { get; set; } 
    public int service_give_special_ticket { get; set; }
    public int service_special_distribution { get; set; }
    public int service_add_gift { get; set; }
    public int service_booking_time { get; set; }
    public int branch_id { get; set; }
    public int service_automatic_transfer { get; set; }
    public int service_automatic_transfer_type { get; set; }
    public int service_automatic_transfer_target { get; set; }
    public int service_automatic_transfer_service_id { get; set; }
    public int service_automatic_transfer_agent_service_id { get; set; }
    public int service_show_vip_button { get; set; }
    public int service_return_to_start { get; set; }
    public int service_return_to_start_interval { get; set; }
    public int service_link { get; set; }
    public int service_link_target { get; set; }
    public int service_separate_agent_selection_button { get; set; }
    public int service_have_print_bg { get; set; }
    public int service_print_bg_picture_id { get; set; }
    public int service_collect_phone_number { get; set; }
    public int service_phone_number_collect_start_number { get; set; }
    public int service_send_sms_client_number { get; set; }
    public int service_do_not_appear_in_close_list { get; set; }
    public int service_show_only_on_normal_menu { get; set; }
    public int service_show_on_vip_menu { get; set; }
    public int service_firm_id { get; set; }
    public int service_ask_closing_code { get; set; }
    public int service_sms_group_id { get; set; }
    public int service_own_advertisement_picture { get; set; }
    public int service_own_print_advertisement_picture { get; set; }
    public int service_own_service_default_wait_time { get; set; }
    public int service_generate_closed_ticket { get; set; }
    public int service_closed_ticket_wait_time { get; set; }
    public int service_closed_ticket_admin_time { get; set; }
    public int service_enable_hide_from_mainframe { get; set; }
    public int service_is_hidden { get; set; }
    public int service_name_blinking { get; set; }
    public int service_order { get; set; }
    public int service_waittime { get; set; }
    public int service_send_to_central { get; set; }
    public int service_invitel_ask_user_type { get; set; }
    public int service_invitel_ask_service_result { get; set; }
    public int service_booking_ticket_id { get; set; }
    public int service_show_waiting_time { get; set; }
    public int service_service_id_for_task { get; set; }
    public int service_language_id { get; set; }
    public int service_is_for_handicapped { get; set; }
    public int service_priority_long_wait { get; set; }
    public int service_long_wait_time { get; set; }
    public int service_allow_feedback { get; set; }
    public int service_scan_document { get; set; }
    public string service_name_in_configuration { get; set; }
    public int service_specialization_id { get; set; }
}
